### ISSUE TITLE
Can we add unicodes to Topcoat comments?

### ISSUE THREAD

**Issue by iuloshi** [cfpb/cf-icons#20]
In the Design Manual Minicon Asset Library, we'd like to include unicodes along with the minicon names. See comp [here](https://github.com/cfpb/design-manual/issues/78#issue-30410007) (& scroll down to the Asset Library section). 

After speaking with @himedlooff, there are several ways this can be formatted in the TopCoat comments. Do you have a preference? Once you decide on the format, I can help with the copy/pasting to add the rest of the unicodes to the comments.

Thanks guys! cc: @Scotchester

**Comment by himedlooff** [comment]
I'm working on this. Stand by.

**Comment by himedlooff** [comment]
So this idea actually addresses more than just the unicode issue. It addresses ignoring irrelevant Topdoc comments like "LESS Variables" and "Icon Class", adding unicode, and grouping icon variations in a more meaningful way (rather than placing their markup together).

The idea here is to stop using Topdoc components as a category grouping and instead use them for each icon. Component patterns would be variations of that icon.

For example instead of:

```
topdoc
  name: Navigation Icons
  patterns:
  - name: Left
    markup: <all left icon variations>
```

We'd do:

```
topdoc
  name: Left
  icon-set: navigation icons
  patterns:
  - name: left
    markup: <default left icon>
  - name: left-round
    markup: <rounded left icon>
```

Here's how it'd look in the Less file:

``` Less
/* topdoc
    name: Left
    family: cf-icons
    icon-set: navigation
    patterns:
    - name: left
      unicode: \e000
      markup: |
        <i class="cf-icon cf-icon-left"></i>
    - name: left-round
      unicode: \e001
      markup: |
        <i class="cf-icon cf-icon-left-round"></i>
    tags:
    - cf-icons
*/

.@{cf-css-prefix}-left:before {
  content: "\e000";
}

.@{cf-css-prefix}-left-round:before {
  content: "\e001";
}

/* topdoc
    name: Right
    family: cf-icons
    icon-set: navigation
    patterns:
    - name: right
      unicode: \e002
      markup: |
        <i class="cf-icon cf-icon-right"></i>
    - name: right-round
      unicode: \e003
      markup: |
        <i class="cf-icon cf-icon-right-round"></i>
    tags:
    - cf-icons
*/

.@{cf-css-prefix}-right:before {
  content: "\e002";
}

.@{cf-css-prefix}-right-round:before {
  content: "\e003";
}
```

I tested this out in the context of the Design Manual and it gives us everything we need. I have not tested this in the context of the Capital Framework generated docs, but this is my next step.
